feature_name: dummy2
args:
  ORG:
    $ref: [spec, org]
  REPO_NAME:
    $ref: [metadata, annotations, firestartr.dev/external-name]

files:
  - src: dummy.md
    dest: dummy2.md
    user_managed: false

patches: {}
